; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -mtriple=amdgcn-amd-amdhsa -mcpu=gfx942 -passes=amdgpu-tdm-descriptor-phi -S < %s | FileCheck %s
; RUN: opt -mtriple=amdgcn-amd-amdhsa -mcpu=gfx942 -passes=amdgpu-tdm-descriptor-phi -amdgpu-tdm-descriptor-phi=false -S < %s | FileCheck %s --check-prefix=DISABLED

; Test TDM descriptor PHI optimization pass.
; This pass transforms TDM descriptor construction in loops to use PHI nodes
; for fields that have affine recurrence patterns, avoiding redundant computation.
; The optimization only triggers when there are at least 2 affine fields.

declare void @llvm.amdgcn.tensor.load.to.lds.d2(<4 x i32>, <8 x i32>, i32 immarg)
declare void @llvm.amdgcn.s.wait.tensorcnt(i16)

@global_smem = external addrspace(3) global [0 x i8]

; ==============================================================================
; Test 1: Two affine fields (should optimize)
; Field 1 (LDS ptr) has affine pattern: {base, +, 8704}
; Field 2 (global_lo) has affine pattern: {base, +, 128}
; Field 3 (global_hi) uses OR - non-affine
; ==============================================================================
define amdgpu_kernel void @test_two_affine_fields(ptr addrspace(1) %global_ptr, i32 %num_iters) {
; CHECK-LABEL: @test_two_affine_fields(
; CHECK:       entry:
; CHECK:         [[LDS_BASE:%.*]] = ptrtoint ptr addrspace(3) @global_smem to i32
; CHECK:         [[GLOBAL_LO_INIT:%.*]] = trunc i64 %global_base to i32
; CHECK:         [[TDM_INIT_1:%.*]] = insertelement <4 x i32> <i32 1, i32 undef, i32 undef, i32 undef>, i32 [[LDS_BASE]], i64 1
; CHECK:         [[TDM_INIT_2:%.*]] = insertelement <4 x i32> [[TDM_INIT_1]], i32 [[GLOBAL_LO_INIT]], i64 2
; CHECK:         br label %loop
; CHECK:       loop:
; CHECK:         [[DESC_PHI:%.*]] = phi <4 x i32> [ [[TDM_INIT_2]], %entry ], [ [[NEXT_DESC:%.*]], %loop ]
; CHECK:         [[TDM_USE:%.*]] = insertelement <4 x i32> [[DESC_PHI]], i32 %global_hi_flag, i64 3
; CHECK:         call void @llvm.amdgcn.tensor.load.to.lds.d2(<4 x i32> [[TDM_USE]],
; CHECK:         [[CUR_1:%.*]] = extractelement <4 x i32> [[DESC_PHI]], i64 1
; CHECK:         [[NEXT_1:%.*]] = add i32 [[CUR_1]], 8704
; CHECK:         [[UPD_1:%.*]] = insertelement <4 x i32> [[DESC_PHI]], i32 [[NEXT_1]], i64 1
; CHECK:         [[CUR_2:%.*]] = extractelement <4 x i32> [[DESC_PHI]], i64 2
; CHECK:         [[NEXT_2:%.*]] = add i32 [[CUR_2]], 128
; CHECK:         [[NEXT_DESC]] = insertelement <4 x i32> [[UPD_1]], i32 [[NEXT_2]], i64 2
;
; DISABLED-LABEL: @test_two_affine_fields(
; DISABLED-NOT:   phi <4 x i32>
; DISABLED:       loop:
; DISABLED:         insertelement <4 x i32> <i32 1,
entry:
  %lds_base = ptrtoint ptr addrspace(3) @global_smem to i32
  %global_base = ptrtoint ptr addrspace(1) %global_ptr to i64

  ; Loop-invariant tensor descriptor
  %tensor_desc = insertelement <8 x i32> <i32 122683392, i32 0, i32 0, i32 8388608, i32 16, i32 128, i32 0, i32 0>, i32 0, i64 1

  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]

  ; Compute LDS offset: IV * 8704 (affine!)
  %lds_offset = mul i32 %iv, 8704
  %lds_ptr = add i32 %lds_base, %lds_offset

  ; Compute global offset: IV * 128 (affine!)
  %global_offset = mul i32 %iv, 128
  %global_offset_64 = zext i32 %global_offset to i64
  %global_addr = add i64 %global_base, %global_offset_64
  %global_lo = trunc i64 %global_addr to i32
  %global_hi_raw = lshr i64 %global_addr, 32
  %global_hi = trunc i64 %global_hi_raw to i32
  %global_hi_flag = or i32 %global_hi, -2147483648

  ; Build address descriptor
  %addr0 = insertelement <4 x i32> <i32 1, i32 poison, i32 poison, i32 poison>, i32 %lds_ptr, i64 1
  %addr1 = insertelement <4 x i32> %addr0, i32 %global_lo, i64 2
  %addr_desc = insertelement <4 x i32> %addr1, i32 %global_hi_flag, i64 3

  call void @llvm.amdgcn.tensor.load.to.lds.d2(<4 x i32> %addr_desc, <8 x i32> %tensor_desc, i32 0)
  call void @llvm.amdgcn.s.wait.tensorcnt(i16 0)

  %iv.next = add i32 %iv, 1
  %cond = icmp ult i32 %iv.next, %num_iters
  br i1 %cond, label %loop, label %exit

exit:
  ret void
}

; ==============================================================================
; Test 2: Only one affine field (should NOT optimize - not worth the PHI overhead)
; Field 1 (LDS) is loop-invariant
; Field 2 (global_lo) has affine pattern
; Field 3 (global_hi) uses OR - non-affine
; ==============================================================================
define amdgpu_kernel void @test_one_affine_field(ptr addrspace(1) %global_ptr, i32 %num_iters) {
; CHECK-LABEL: @test_one_affine_field(
; CHECK-NOT:   phi <4 x i32>
; CHECK:       loop:
; CHECK:         insertelement <4 x i32> <i32 1,
;
; DISABLED-LABEL: @test_one_affine_field(
; DISABLED-NOT:   phi <4 x i32>
entry:
  %lds_base = ptrtoint ptr addrspace(3) @global_smem to i32
  %global_base = ptrtoint ptr addrspace(1) %global_ptr to i64

  %tensor_desc = insertelement <8 x i32> <i32 122683392, i32 0, i32 0, i32 8388608, i32 16, i32 128, i32 0, i32 0>, i32 0, i64 1

  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]

  ; Only global_lo is affine
  %global_offset = mul i32 %iv, 16384
  %global_offset_64 = zext i32 %global_offset to i64
  %global_addr = add i64 %global_base, %global_offset_64
  %global_lo = trunc i64 %global_addr to i32
  %global_hi_raw = lshr i64 %global_addr, 32
  %global_hi = trunc i64 %global_hi_raw to i32
  %global_hi_flag = or i32 %global_hi, -2147483648

  ; LDS base is invariant (not affine)
  %addr0 = insertelement <4 x i32> <i32 1, i32 poison, i32 poison, i32 poison>, i32 %lds_base, i64 1
  %addr1 = insertelement <4 x i32> %addr0, i32 %global_lo, i64 2
  %addr_desc = insertelement <4 x i32> %addr1, i32 %global_hi_flag, i64 3

  call void @llvm.amdgcn.tensor.load.to.lds.d2(<4 x i32> %addr_desc, <8 x i32> %tensor_desc, i32 0)
  call void @llvm.amdgcn.s.wait.tensorcnt(i16 0)

  %iv.next = add i32 %iv, 1
  %cond = icmp ult i32 %iv.next, %num_iters
  br i1 %cond, label %loop, label %exit

exit:
  ret void
}

; ==============================================================================
; Test 3: Non-affine field (should not optimize)
; Field 2 uses OR instead of ADD, making it non-affine
; ==============================================================================
define amdgpu_kernel void @test_non_affine_field(ptr addrspace(1) %global_ptr, i32 %num_iters, i32 %base_offset) {
; CHECK-LABEL: @test_non_affine_field(
; CHECK-NOT:   phi <4 x i32>
; CHECK:       loop:
; CHECK:         or i32 {{.*}}, %base_offset
; CHECK:         insertelement <4 x i32> <i32 1,
;
; DISABLED-LABEL: @test_non_affine_field(
; DISABLED-NOT:   phi <4 x i32>
entry:
  %lds_base = ptrtoint ptr addrspace(3) @global_smem to i32
  %global_base = ptrtoint ptr addrspace(1) %global_ptr to i64

  %tensor_desc = insertelement <8 x i32> <i32 122683392, i32 0, i32 0, i32 8388608, i32 16, i32 128, i32 0, i32 0>, i32 0, i64 1

  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]

  ; Non-affine: uses OR instead of ADD
  %iv_shifted = shl i32 %iv, 7
  %offset_or = or i32 %iv_shifted, %base_offset   ; <-- OR makes this non-affine
  %global_offset = shl i32 %offset_or, 7
  %global_offset_64 = zext i32 %global_offset to i64
  %global_addr = add i64 %global_base, %global_offset_64
  %global_lo = trunc i64 %global_addr to i32
  %global_hi_raw = lshr i64 %global_addr, 32
  %global_hi = trunc i64 %global_hi_raw to i32
  %global_hi_flag = or i32 %global_hi, -2147483648

  %addr0 = insertelement <4 x i32> <i32 1, i32 poison, i32 poison, i32 poison>, i32 %lds_base, i64 1
  %addr1 = insertelement <4 x i32> %addr0, i32 %global_lo, i64 2
  %addr_desc = insertelement <4 x i32> %addr1, i32 %global_hi_flag, i64 3

  call void @llvm.amdgcn.tensor.load.to.lds.d2(<4 x i32> %addr_desc, <8 x i32> %tensor_desc, i32 0)
  call void @llvm.amdgcn.s.wait.tensorcnt(i16 0)

  %iv.next = add i32 %iv, 1
  %cond = icmp ult i32 %iv.next, %num_iters
  br i1 %cond, label %loop, label %exit

exit:
  ret void
}

; ==============================================================================
; Test 4: Multiple TDM calls with two affine fields each
; Each call should get its own independent PHI
; ==============================================================================
define amdgpu_kernel void @test_multiple_calls_two_affine(ptr addrspace(1) %global_ptr_a, ptr addrspace(1) %global_ptr_b, i32 %num_iters) {
; CHECK-LABEL: @test_multiple_calls_two_affine(
; CHECK:       loop:
; CHECK:         [[PHI_A:%.*]] = phi <4 x i32>
; CHECK:         [[PHI_B:%.*]] = phi <4 x i32>
; CHECK:         call void @llvm.amdgcn.tensor.load.to.lds.d2
; CHECK:         call void @llvm.amdgcn.tensor.load.to.lds.d2
; CHECK:         extractelement <4 x i32> [[PHI_A]], i64 1
; CHECK:         add i32 {{.*}}, 8704
; CHECK:         extractelement <4 x i32> [[PHI_A]], i64 2
; CHECK:         add i32 {{.*}}, 16384
;
; DISABLED-LABEL: @test_multiple_calls_two_affine(
; DISABLED-NOT:   phi <4 x i32>
entry:
  %lds_base = ptrtoint ptr addrspace(3) @global_smem to i32
  %global_base_a = ptrtoint ptr addrspace(1) %global_ptr_a to i64
  %global_base_b = ptrtoint ptr addrspace(1) %global_ptr_b to i64

  %tensor_desc = insertelement <8 x i32> <i32 122683392, i32 0, i32 0, i32 8388608, i32 16, i32 128, i32 0, i32 0>, i32 0, i64 1

  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]

  ; First TDM call (tensor A) - two affine fields
  %lds_offset_a = mul i32 %iv, 8704
  %lds_ptr_a = add i32 %lds_base, %lds_offset_a
  %offset_a = mul i32 %iv, 16384
  %offset_a_64 = zext i32 %offset_a to i64
  %addr_a = add i64 %global_base_a, %offset_a_64
  %lo_a = trunc i64 %addr_a to i32
  %hi_raw_a = lshr i64 %addr_a, 32
  %hi_a = trunc i64 %hi_raw_a to i32
  %hi_flag_a = or i32 %hi_a, -2147483648

  %desc_a0 = insertelement <4 x i32> <i32 1, i32 poison, i32 poison, i32 poison>, i32 %lds_ptr_a, i64 1
  %desc_a1 = insertelement <4 x i32> %desc_a0, i32 %lo_a, i64 2
  %desc_a = insertelement <4 x i32> %desc_a1, i32 %hi_flag_a, i64 3

  call void @llvm.amdgcn.tensor.load.to.lds.d2(<4 x i32> %desc_a, <8 x i32> %tensor_desc, i32 0)

  ; Second TDM call (tensor B) - two affine fields
  %lds_offset_b = mul i32 %iv, 4352
  %lds_ptr_b = add i32 %lds_base, %lds_offset_b
  %offset_b = mul i32 %iv, 8192
  %offset_b_64 = zext i32 %offset_b to i64
  %addr_b = add i64 %global_base_b, %offset_b_64
  %lo_b = trunc i64 %addr_b to i32
  %hi_raw_b = lshr i64 %addr_b, 32
  %hi_b = trunc i64 %hi_raw_b to i32
  %hi_flag_b = or i32 %hi_b, -2147483648

  %desc_b0 = insertelement <4 x i32> <i32 1, i32 poison, i32 poison, i32 poison>, i32 %lds_ptr_b, i64 1
  %desc_b1 = insertelement <4 x i32> %desc_b0, i32 %lo_b, i64 2
  %desc_b = insertelement <4 x i32> %desc_b1, i32 %hi_flag_b, i64 3

  call void @llvm.amdgcn.tensor.load.to.lds.d2(<4 x i32> %desc_b, <8 x i32> %tensor_desc, i32 0)
  call void @llvm.amdgcn.s.wait.tensorcnt(i16 0)

  %iv.next = add i32 %iv, 1
  %cond = icmp ult i32 %iv.next, %num_iters
  br i1 %cond, label %loop, label %exit

exit:
  ret void
}
